### PR TITLE
Add Mir 2.11.0 info to compositor support table

### LINKED ISSUE #13: Mir compositor compatabilities missing
Mir is a Wayland compositor library that provides a simple high-level API for building shells.
Upstream: https://github.com/MirServer/mir

image
Example: [wp_viewporter's compositor support](https://wayland.app/protocols/viewporter#compositor-support)

### PR DESCRIPTION
**Pull request by JamiKettunen**
Logo is "Circle of Friends" from https://design.ubuntu.com/downloads/ (https://assets.ubuntu.com/v1/ce518a18-CoF-2022_solid+O.svg) with color `#e9500e` modified to `#000000`.

Marking as a draft until confirmation from @AlanGriffiths regarding the logo choice being correct is gotten; using a placeholder for now though since https://mir-server.io/ shows it too for example.

Closes #13.

### CODE REVIEW

**Comment by JamiKettunen** [comment]
[Looks serviceable imho](https://deploy-preview-19--wayland-explorer.netlify.app/protocols/wayland#compositor-support), thoughts?
image

**Comment by JamiKettunen** [comment]
Rebased to fix merge conflict and ran `wlprobe` on `mir_demo_server` instead of `mir-shell` as per Alan's comment:
> The extensions enabled are configurable. Some are disabled by default (and typically only advised to recognised clients). Also, shells can add their own.
>
> Only `mir_demo_server` defaults to enabling all of them

**Comment by AlanGriffiths** [comment]
> Marking as a draft until confirmation from @AlanGriffiths regarding the logo choice being correct

Confirmed

**Comment by JamiKettunen** [comment]
@vially This should be ready to merge now unless you have feedback ^^

**Review by vially — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
