### PR TITLE
Add Weston 11.0.1 info to compositor support table

### LINKED ISSUE #14: Weston compositor compatabilities missing
Weston is the reference implementation of a Wayland compositor.
Upstream: https://gitlab.freedesktop.org/wayland/weston

image
Example: [wp_viewporter's compositor support](https://wayland.app/protocols/viewporter#compositor-support)

### PR DESCRIPTION
**Pull request by JamiKettunen**
Logo is https://gitlab.freedesktop.org/wayland/weston/-/blob/master/data/wayland.svg with `style` line for `#ffbc00` (yellow circle) removed.

Closes #14.

### CODE REVIEW

**Comment by JamiKettunen** [comment]
[Looks serviceable imho](https://deploy-preview-18--wayland-explorer.netlify.app/protocols/wayland#compositor-support), thoughts?
image

**Comment by JamiKettunen** [comment]
I noticed there's no way to tell what version of the compositor the marketed features are available on, they're just updated "sometimes" as seen in e.g. #17; I think at least a mouse hover on the text / logo showing the version of the compositor would be a very nice addition.

**Comment by JamiKettunen** [comment]
Heh finally some of the Weston unstable entries have one supported compositor ^^
image

**Comment by JamiKettunen** [comment]
Fancy, also implements `input-method-unstable-v1` already
image

**Comment by vially** [comment]
This looks great, thanks a lot!

> noticed there's no way to tell what version of the compositor the marketed features are available on

Agree, that would be a nice addition.

**Review by vially — APPROVED** [review]

**Pull request merged**
