### PR TITLE
Add dark mode

### PR DESCRIPTION
**Pull request by PolyMeilex**
Hi! First of all, thank you for an amazing tool!

I wrote super simple dark mode for my personal use, but I thought that you may be interested in merging it upstream, so here I am.
img

~~EDIT: oh it turns out that I introduced a little bit of regression on mobile version, sorry for that I will fix it tomorrow~~ (fixed)

### CODE REVIEW

**Comment by vially** [comment]
I'll come back with a proper review soon but I think this is looking great :100:.

Thanks a lot for working on it!

**Review by vially — APPROVED** [review]
First of all, the dark mode itself is looking great (also the fancy scroll-bars are a very nice touch so I've enabled them for `light` mode as well).

However, I found a small issue related to the `darkMode: 'class'` Tailwind config so I pushed a new commit to your branch (hope you don't mind) which reverted it to the `media` value. Unfortunately this also means I had to remove the light/dark mode toggle button. So the only way to enable the dark mode version is by enabling it globally in your OS or forcing it for your browser (e.g.: using Chrome's `--force-dark-mode` command-line flag).

The problem with using the `class` option is that it breaks dark mode when running with JavaScript disabled. I haven't personally found the arguments to disable JavaScript convincing enough, but I do know some people have strong opinions about this so I would like to continue supporting it _when possible_.

Ideally, it would be nice if Tailwind supported both the `media` and `class` options at the same time but it looks like that's not currently possible (https://github.com/tailwindlabs/tailwindcss/discussions/3644).

So it's either `class` but lose the dark mode when JavaScript is disabled, or `media` but lose the ability to let the user overwrite it on a per-website basis. For now I would prefer the latter but I don't have strong opinions about it so if you think the `class` options is better I'm happy to bring it back.

If not, I'll just merge this pull-request as is and we can keep an eye out for possible solutions to bring the toggle button back.

**Comment by PolyMeilex** [comment]
Yeah, I totally get you're point, without changes to tailwind there is probably not much we can do about that. We can merge it as it

**Comment by PolyMeilex** [comment]
Thanks! :grin:

**Comment by vially** [comment]
Awesome! Thanks a lot for your work. The dark mode looks really nice!

**Pull request merged**
